
language: cpp
dist: trusty

git:
  submodules: false

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - libhdf5-serial-dev
    - libfftw3-dev
    - libzip-dev

install:
 - pwd
 - echo -e "machine github.com login jbcm627-travis password Z8wrU3RuBRuM6steQE7e" >> ~/.netrc
 - git submodule update --init --recursive
 - gcc --version
 - g++ --version

before_script:
 - export OMP_NUM_THREADS=4

script: scripts/run_tests.sh
